name: Release using conventional commits
#this action will run on the merge to master for any changes to the code that manages the AWS SSO resources and generate a release tag
#there are MS Teams channels (CAB) that subscribe to those release notifications

on:
  push:
    branches:
      - master
    paths:
      - 'applied/accounts/global/us-east-1/awssso/**'
      - 'infrastructure/region/awssso/**'
      - '!**.md'    # do not run the job when only changing markdown files   

jobs:
  release-tag:
    runs-on: ubuntu-20.04
    permissions:
      contents: write   # write permissions is needed in order to create release in the master branch
      
    steps:
      # It is required to have a checkout step prior to changelog and release step,to allow action to discover the configuration file.   
      - uses: actions/checkout@v2
        with:
          # This is needed to retrieve all commits history in a single branch with 200 being the maximum fetch-depth
          # using fetch-depth "0" gets all commit history for all branches and tags in the repository which we didn't need and felt was an expansive operation
          fetch-depth: "200"
             
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
       
      - name: Create releases
        uses:  ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body : ${{ steps.tag_version.outputs.changelog }}

